version: '3'
services:
#### APP em node
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./:/app/
    command: npm run dev
    networks:
      - webhook_net
  
#### RabbitMQ  
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file: 
      - .env
    networks:
      - webhook_net

#### MongoDB
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"     
    env_file: 
      - .env
    networks:
      - webhook_net
#### Mongo Express
  mogno-Express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment: 
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017
      - ME_CONFIG_MONGODB_DB=${DB_NAME}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DB_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DB_PASS}
     #- ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_PORT=${DB_PORT}
      - ME_CONFIG_MONGODB_AUTH_DATABASE=${DB_USER}
    networks:
      - webhook_net


#### networks all containers
networks:
  webhook_net: